# Generated by Django 4.2.5 on 2023-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_studet_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
