# Generated by Django 4.2.5 on 2023-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='props',
            field=models.TextField(blank=True),
        ),
    ]
